In [2]:
from datascience import *
import numpy as np
#Array of PI
pi = make_array("Koby","Hinnant","May 7th, 1998", "Blue")

In [3]:
pi

array(['Koby', 'Hinnant', 'May 7th, 1998', 'Blue'], dtype='<U13')

In [7]:
#Capitalizing all the PI
np.char.upper(pi)

array(['KOBY', 'HINNANT', 'MAY 7TH, 1998', 'BLUE'], dtype='<U13')

In [22]:
#Counting "a" in each index of the array
np.char.count(pi,"a")

array([0, 1, 1, 0])

In [42]:
# Every other odd number to 45 in an array
odds = np.arange(1,47,4)
odds = odds.astype(float)
odds

array([ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37., 41., 45.])

In [43]:
#Product of every index in the array
np.prod(odds)

341094033905625.0

In [39]:
#sum of every index in the array
np.sum(odds)

276

In [44]:
#array of the sums of the adjacent numbers in the array
first = odds[0:len(odds)-1]
second = odds[1:len(odds)]
adj = first + second
adj

array([ 6., 14., 22., 30., 38., 46., 54., 62., 70., 78., 86.])